# Travis-CI configuration file for SuperTuxKart
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
language: cpp
compiler:
  - gcc
# - clang
#branches:
#  only:
#    - master
before_install:
  # UPDATE REPOS
  - sudo apt-get update -qq
  # INSTALL DEPENDENCIES
  - sudo apt-get install build-essential cmake libogg-dev libvorbis-dev libopenal-dev libxxf86vm-dev libgl1-mesa-dev libglu1-mesa-dev libcurl4-openssl-dev libfribidi-dev libbluetooth-dev
script:
  #  BUILD COMMANDS
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make VERBOSE=1 -j 4 
# notifications:
  # irc:
    # channels:
      # - "irc.freenode.org#stk"
    # skip_join: false
    # use_notice: true
    # template:
      # #- "[%{commit}: %{author}] %{message}"
      # #- "%{build_url}"
      # - "[%{repository}#%{branch} @%{commit}] %{author}): %{message}"
      # - "Diff: %{compare_url}"
      # - "Build: %{build_url}"
